#%RAML 1.0 DataType
type: object
description: Data Type of Order object
properties:
  customerID: 
    type: integer
  customerName:
    type: string
    required: false
  vuvuzelaType:
    type: string
    enum: [A, B, C]
  vuvuzelaAmount:
    type: integer


    
  